// Restaurant data - Edit this file to add more restaurants
const restaurants = [
  {
    id: 1,
    name: "小满飯糰",
    englishName: "Xiaoman Riceburrito",
    address: "573 E El Camino Real, Sunnyvale, CA",
    lat: 37.3688,
    lng: -122.0363,
    cuisine: "Taiwanese Breakfast",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 2,
    name: "京味轩",
    englishName: "Taste Good Beijing Cuisine",
    address: "76 S Abel St, Milpitas, CA",
    lat: 37.4323,
    lng: -121.9007,
    cuisine: "Beijing / Northern Chinese",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 3,
    name: "天惠居",
    englishName: "Famous Food Restaurant",
    address: "872 Old San Francisco Rd, Sunnyvale, CA 94086",
    lat: 37.3564,
    lng: -122.0206,
    cuisine: "Tianjin-style Chinese",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 4,
    name: "Keke's Breakfast Cafe",
    englishName: "Keke's Breakfast Cafe",
    address: "311 S Mathilda Ave, Sunnyvale, CA 94086",
    lat: 37.3722,
    lng: -122.0307,
    cuisine: "American Breakfast",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 5,
    name: "杨国福麻辣烫",
    englishName: "YGF Malatang Noodles & Pots",
    address: "19672 Stevens Creek Blvd, Cupertino, CA",
    lat: 37.3230,
    lng: -122.0098,
    cuisine: "Malatang / Hot Pot",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 6,
    name: "张亮麻辣烫",
    englishName: "Zhangliang Malatang",
    address: "246 Castro St, Mountain View, CA 94041",
    lat: 37.3940,
    lng: -122.0790,
    cuisine: "Malatang / Hot Pot",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 7,
    name: "小香牛骨米粉",
    englishName: "Hunan Mifen",
    address: "592 E El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3691,
    lng: -122.0336,
    cuisine: "Hunan Rice Noodles",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 8,
    name: "自选麻辣烫",
    englishName: "Mala Town",
    address: "438 Barber Ln, Milpitas, CA 95035",
    lat: 37.4165,
    lng: -121.9225,
    cuisine: "Malatang / Hot Pot",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 9,
    name: "Dana包子铺",
    englishName: "Danacious Dumplings",
    address: "375 Saratoga Ave M, San Jose, CA",
    lat: 37.3195,
    lng: -121.9680,
    cuisine: "Chinese Dumplings / Baozi",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 10,
    name: "川悦麻辣烫",
    englishName: "CUANYUE Mala Moment",
    address: "1036 E El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3521,
    lng: -122.0055,
    cuisine: "Malatang / Hot Pot",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 11,
    name: "The Skewer Bar",
    englishName: "The Skewer Bar",
    address: "3082 Landess Ave, San Jose, CA 95132",
    lat: 37.4076,
    lng: -121.8585,
    cuisine: "Chinese BBQ Skewers",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 12,
    name: "やよい軒",
    englishName: "Yayoi",
    address: "20684 Homestead Rd, Cupertino, CA 95014",
    lat: 37.3411,
    lng: -122.0190,
    cuisine: "Japanese Teishoku",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 13,
    name: "Popeyes",
    englishName: "Popeyes Louisiana Kitchen",
    address: "816 W El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3688,
    lng: -122.0492,
    cuisine: "American Fast Food / Fried Chicken",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 14,
    name: "McDonald's",
    englishName: "McDonald's",
    address: "1060 E El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3509,
    lng: -122.0030,
    cuisine: "American Fast Food",
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 15,
    name: "塔里木新疆风味",
    englishName: "Tarim Garden Xinjiang Cuisine",
    address: "768 Barber Ln, Milpitas, CA 95035",
    lat: 37.4185,
    lng: -121.9178,
    cuisine: "Xinjiang / Uyghur Chinese",
    rating: 0,
    notes: "",
    dateVisited: ""
  }
];
